# korean_names.py
# 영어 폴더명(Kaggle 데이터셋 기준) → 한국어 포켓몬 이름 매핑
# 키: ImageFolder가 읽는 폴더명 (대소문자 구분)
# 데이터셋에 없는 포켓몬은 fallback으로 영어 이름을 그대로 출력

KOREAN_NAMES = {
    "Abra":         "케이시",
    "Aerodactyl":   "프테라",
    "Alakazam":     "후딘",
    "Arbok":        "아보크",
    "Arcanine":     "윈디",
    "Articuno":     "루gia",   # 프리져
    "Articuno":     "프리져",
    "Beedrill":     "독침붕",
    "Bellsprout":   "모다피",
    "Blastoise":    "거북왕",
    "Bulbasaur":    "이상해씨",
    "Butterfree":   "버터플",
    "Caterpie":     "캐터피",
    "Chansey":      "럭키",
    "Charizard":    "리자몽",
    "Charmander":   "파이리",
    "Charmeleon":   "리자드",
    "Clefable":     "픽시",
    "Clefairy":     "삐삐",
    "Cloyster":     "파르셀",
    "Cubone":       "탕구리",
    "Dewgong":      "쥬레곤",
    "Diglett":      "디그다",
    "Ditto":        "메타몽",
    "Dodrio":       "두트리오",
    "Doduo":        "두두",
    "Dragonair":    "신뇽",
    "Dragonite":    "망나뇽",
    "Dratini":      "미뇽",
    "Drowzee":      "슬리프",
    "Dugtrio":      "닥트리오",
    "Eevee":        "이브이",
    "Ekans":        "아보",
    "Electabuzz":   "에레브",
    "Electrode":    "붐볼",
    "Exeggcute":    "아라리",
    "Exeggutor":    "나시",
    "Farfetchd":    "파오리",
    "Fearow":       "깨비드릴조",
    "Flareon":      "부스터",
    "Gastly":       "고오스",
    "Gengar":       "팬텀",
    "Geodude":      "꼬마돌",
    "Gloom":        "냄새꼴",
    "Golbat":       "골뱃",
    "Goldeen":      "콘치",
    "Golduck":      "골덕",
    "Golem":        "딱구리",
    "Graveler":     "데구리",
    "Grimer":       "질퍽이",
    "Growlithe":    "가디",
    "Gyarados":     "갸라도스",
    "Haunter":      "고우스트",
    "Hitmonchan":   "홍수몬",
    "Hitmonlee":    "시라소몬",
    "Horsea":       "쏘드라",
    "Hypno":        "슬리퍼",
    "Ivysaur":      "이상해풀",
    "Jigglypuff":   "푸린",
    "Jolteon":      "썬더",
    "Jynx":         "루주라",
    "Kabuto":       "투구",
    "Kabutops":     "투구푸스",
    "Kadabra":      "윤겔라",
    "Kakuna":       "딱충이",
    "Kangaskhan":   "캥카",
    "Kingler":      "킹크랩",
    "Koffing":      "또가스",
    "Krabby":       "크랩",
    "Lapras":       "라프라스",
    "Lickitung":    "내룸손",
    "Machamp":      "괴력몬",
    "Machoke":      "근육몬",
    "Machop":       "알통몬",
    "Magikarp":     "잉어킹",
    "Magmar":       "마그마",
    "Magnemite":    "코일",
    "Magneton":     "레어코일",
    "Mankey":       "망키",
    "Marowak":      "텅구리",
    "Meowth":       "나옹",
    "Metapod":      "단데기",
    "Mew":          "뮤",
    "Mewtwo":       "뮤츠",
    "Moltres":      "파이어",
    "Mr. Mime":     "마임맨",
    "Mr-mime":      "마임맨",
    "Mrmime":       "마임맨",
    "Muk":          "질뻐기",
    "Nidoking":     "니드킹",
    "Nidoqueen":    "니드퀸",
    "Nidoran-f":    "니드런♀",
    "Nidoran-m":    "니드런♂",
    "Nidoranf":     "니드런♀",
    "Nidoranm":     "니드런♂",
    "Nidorina":     "니드리나",
    "Nidorino":     "니드리노",
    "Ninetales":    "나인테일",
    "Oddish":       "뚜벅초",
    "Omanyte":      "암나이트",
    "Omastar":      "암스타",
    "Onix":         "롱스톤",
    "Paras":        "파라스",
    "Parasect":     "파라섹트",
    "Persian":      "페르시온",
    "Pidgeot":      "피죤투",
    "Pidgeotto":    "피죤",
    "Pidgey":       "구구",
    "Pikachu":      "피카츄",
    "Pinsir":       "쁘사이저",
    "Poliwag":      "발챙이",
    "Poliwrath":    "강챙이",
    "Poliwhirl":    "슈륙챙이",
    "Ponyta":       "포니타",
    "Porygon":      "폴리곤",
    "Primeape":     "성원숭",
    "Psyduck":      "꼬댕이",
    "Raichu":       "라이츄",
    "Rapidash":     "날쌩마",
    "Raticate":     "레트라",
    "Rattata":      "꼬렛",
    "Rhydon":       "코뿌리",
    "Rhyhorn":      "뿔카노",
    "Sandshrew":    "모래두지",
    "Sandslash":    "고지",
    "Scyther":      "스라크",
    "Seadra":       "seadra",
    "Seaking":      "왕콘치",
    "Seel":         "쥬쥬",
    "Shellder":     "셀러",
    "Slowbro":      "야도란",
    "Slowpoke":     "야돈",
    "Snorlax":      "잠만보",
    "Spearow":      "깨비참",
    "Squirtle":     "꼬부기",
    "Starmie":      "아쿠스타",
    "Staryu":       "별가사리",
    "Tangela":      "덩쿠리",
    "Tauros":       "켄타로스",
    "Tentacool":    "왕눈해",
    "Tentacruel":   "독파리",
    "Vaporeon":     "샤워즈",
    "Venomoth":     "도나리",
    "Venonat":      "콘팡",
    "Venusaur":     "이상해꽃",
    "Victreebel":   "우츠보트",
    "Vileplume":    "라플레시아",
    "Voltorb":      "찌리리공",
    "Vulpix":       "식스테일",
    "Wartortle":    "어니부기",
    "Weedle":       "뿔충이",
    "Weepinbell":   "우츠동",
    "Weezing":      "또도가스",
    "Wigglytuff":   "푸크린",
    "Zapdos":       "썬더",
    "Zubat":        "주뱃",
}

def get_korean_name(english_name: str) -> str:
    """
    영어 포켓몬 이름을 받아 한국어 이름을 반환합니다.
    매핑이 없으면 영어 이름을 그대로 반환합니다.
    """
    # 그대로 찾기
    if english_name in KOREAN_NAMES:
        return KOREAN_NAMES[english_name]
    # 대소문자 무시하고 찾기
    for key, val in KOREAN_NAMES.items():
        if key.lower() == english_name.lower():
            return val
    # 매핑 없으면 영어 이름 반환
    return english_name
